### PR TITLE
RELEASE

### PR DESCRIPTION
**Pull request by ch40s3k**

### CODE REVIEW

**Comment by benethor** [comment]
Coverage decreased (-11.09%) to 32.85% 

wat...

**Comment by ch40s3k** [comment]
There is no tests

**Comment by benethor** [comment]
@ch40s3k my point exactly. Do something about it :P

**Comment by h00dy** [comment]
+1, test will be done in another PR. Right now we are blocked with other tools.

**Comment by pawellesniewski** [comment]
📟

**Pull request merged**
